export const notes = [
    {
        id:1,
        name:"scene1",
        textpart1:"In the vast expanse of the universe, there exists a cluster of shimmering nebulas", 
        textpart2: "known as the Hikaru Stellar Hatchery—a birthplace of mysterious, sentient life forms called Korokoro.",
        imagesource: "space1-600.png",
    },
    {
        id:2,
        name:"scene2",
        textpart1:"These tiny creatures are born within radiant eggs, absorbing the energy of nearby stars", 
        textpart2: "to develop their unique personalities and powers.",
        imagesource: "space2-600.png",
    },
    {
        id:3,
        name:"scene3",
        textpart1:"One day, three unfortunate Korokoro eggs were cast adrift from the hatchery", 
        textpart2: " by gigantic, a cosmic storm.",
        imagesource: "space3-600.png",
    },
    {
        id:4,
        name:"scene4",
        textpart1:"Involuntarily, they were travelling across the universe ...", 
        textpart2: " ",
        imagesource: "space4-600.png",
    },
    {
        id:5,
        name:"scene5",
        textpart1:"... until they landed on Earth.", 
        textpart2: "",
        imagesource: "earth1-600.png",
    },
    {
        id:6,
        name:"scene6",
        textpart1:"Together with two friends, you are strolling thorugh a neighbouring forest.", 
        textpart2: "Suddenly, you stumble unto the Korokoro eggs.",
        imagesource: "earth2-600.png",
    },
    {
        id:7,
        name:"scene7",
        textpart1:"Finally, you decide that each of you shall take care of one of the eggs.", 
        textpart2: "",
        imagesource: "earth3-600.png",
    },
]